wip
lifebit-ai/cloudos pull request #13
Opened 2020-11-06 10:01 UTC by sk-sahu

2020-11-13 13:35 UTC, sk-sahu commented
First merge - https://github.com/lifebit-ai/cloudos/pull/17 then this one.

2020-11-26 17:14 UTC, sk-sahu reviewed
Self reviewed.

2020-12-01 09:39 UTC, cgpu commented on R/cb_cohort_extract.R
>    }else{
Note here if it can be replaced with a more explicit if statement.

2020-12-01 09:42 UTC, cgpu commented on R/cb_cohort_extract.R
> +  rownames(res_df_new) <- 1:page_size
Can we make it illegal and stop with error when a `page_size` == 0?

2020-12-01 09:45 UTC, cgpu commented on R/cb_cohorts_list.R
> +  httr::stop_for_status(r, task = "list cohorts")
Maybe an error that more explicitly points to the function would be helpful in a scenario that a user is not directly running the function but calling it from a wrapper script?
 
```diff
- Error in function `cloudos::cb_cohorts_list()`
```

2020-12-01 09:46 UTC, cgpu commented on R/cb_filter_apply.R
> +# .build_filter_body(filter_query = list("22" = list("from" = "2015-05-13", "to" = "2016-04-29"), "50" = c("Father", "Mother")))
Cleanup for comments and migrate commands to vignette.

2020-12-01 09:49 UTC, cgpu commented on R/cb_filter_explore.R
> +  if(length(filters) == 0) stop(message("No phenotypic filters found with - ", term ))
To check if `stop(message())` is good practice. Eg search in GitHub for other people using it or  StackOverflow.

2020-12-01 09:50 UTC, cgpu commented on R/cb_json.R
>  # Column JOSN
Consider adding Roxygen2 comments for internal functions.

2020-12-01 09:53 UTC, cgpu commented on R/cb_json.R
> +                    "array" = col$array # make sure toJSON(auto_unbox = T)
Check where does this comment refer to.

2020-12-01 09:53 UTC, cgpu commented on R/cb_json.R
>  # TODO work on column - At this point NO end-point that returns this information, there are cards
Check if this is needed

2020-12-01 09:54 UTC, cgpu commented on R/cb_json.R
> +    }else{
Check if we can be more explicit with if

2020-12-01 09:55 UTC, cgpu commented on README.Rmd
> +For this a `filter_query` is required.
@cgpu to test README.md commands.

2020-12-01 09:57 UTC, cgpu requested changes
Added comments. Looks good!

Check notes and update changelog to reflect changes.

2021-02-16 09:44 UTC, sk-sahu commented on R/cb_filter_explore.R
> +  if(length(filters) == 0) stop(message("No phenotypic filters found with - ", term ))
replaced with `httr::stop_for_status()`

2021-02-16 14:09 UTC, sk-sahu commented on R/cb_cohort_extract.R
>    }else{
This creates empty list objects to hold the values

2021-02-16 14:24 UTC, sk-sahu commented on R/cb_cohort_extract.R
> +  rownames(res_df_new) <- 1:page_size
This is a good suggestion. Thanks! Addressed https://github.com/lifebit-ai/cloudos/pull/13/commits/c0b28bbcdc7c34c48ad5b6d4a486baeda4f28594

2021-02-16 14:49 UTC, sk-sahu commented on R/cb_filter_apply.R
> +# .build_filter_body(filter_query = list("22" = list("from" = "2015-05-13", "to" = "2016-04-29"), "50" = c("Father", "Mother")))
cleaned

2021-02-16 14:59 UTC, sk-sahu commented on R/cb_json.R
>  # Column JOSN
https://github.com/lifebit-ai/cloudos/pull/13/commits/f2467d3f56cee1255f7b61e8405217b208e356f8

2021-02-16 18:46 UTC, sk-sahu commented on R/cb_json.R
> +                    "array" = col$array # make sure toJSON(auto_unbox = T)
This comment refers to same line and I suppose this is allowed!!

2021-02-16 18:46 UTC, sk-sahu commented on R/cb_json.R
>  # TODO work on column - At this point NO end-point that returns this information, there are cards
This endpoint suppose to be coming

2021-02-17 13:28 UTC, merged