Feature filter api
lifebit-ai/cloudos pull request #6
Opened 2020-08-19 18:47 UTC by sk-sahu

2020-09-01 14:29 UTC, sk-sahu commented
As we (@Vlad-Dembrovskyi , @aldembert and me) had a discussion last Friday, most of them are same but major changes based on @Vlad-Dembrovskyi's input are - 
* A cohort object, which can be passed to all cohort related functions.
* Get samples table for a particular cohort with applied filters.

2020-09-03 14:54 UTC, cgpu requested changes
We need:

- unit tests for the functions
- reproducible dummy examples so that we can internally at a first instance test

I am suggesting to hold off merging until we have tests and examples, unless there is an urgent need to merge.

2020-09-16 14:30 UTC, sk-sahu commented
Include UX feedbacks - https://app.zenhub.com/workspaces/lifebit-platform-5aa6276b1224bb03d13f0e82/issues/lifebit-ai/lifebit-platform/10156

2020-09-30 13:40 UTC, cgpu commented on R/cb_plots.R
> +        my_value_color <- c(my_value_color, "green")
Could use the hex codes from the web app for extra style points :sparkles:

2020-09-30 13:42 UTC, cgpu commented on R/create_cohort.R
> -#' @title Create Cohort
Replaced by `cb_`

2020-10-02 10:14 UTC, sk-sahu commented
@cgpu Just added `pkgdown.yaml` so that we can safely clean this `docs` folder (which is becoming lot of files to keep track in commits and during review). 

From github-actions, It will push the master branch push pkgdown updates to a new `gh-branch`

2020-10-02 17:29 UTC, cgpu approved these changes
Good to go! :neckbeard: 

Squash it, and right after create a new branch named `plots-improvements` so that we don't forget about those.

2020-10-02 17:31 UTC, merged